
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pos.pmfuncs.MainFunc;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * 
 */
public class PromoFrame extends javax.swing.JFrame {
    JFrame framePro;
    String [] Cdetail = new String [2];
    /**
     * Creates new form PromoFrame
     */
    public PromoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discountSet = new javax.swing.JButton();
        proPercent = new javax.swing.JLabel();
        proTitle = new javax.swing.JLabel();
        couponSet = new javax.swing.JButton();
        couponText = new javax.swing.JTextField();
        folderCombo = new javax.swing.JComboBox();
        couponName = new javax.swing.JLabel();
        proName = new javax.swing.JLabel();
        discountText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        currCouponLabel = new javax.swing.JLabel();
        currCouponText = new javax.swing.JTextField();
        currCouponDiscount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CouponDiscount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        discountSet.setText("Set");
        discountSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discountSetMouseClicked(evt);
            }
        });
        discountSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountSetActionPerformed(evt);
            }
        });

        proPercent.setText("%");

        proTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        proTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proTitle.setText("PROMOTION");

        couponSet.setText("Set");
        couponSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                couponSetMouseClicked(evt);
            }
        });
        couponSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couponButtonActionPerformed(evt);
            }
        });

        couponText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couponCodeActionPerformed(evt);
            }
        });

        folderCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "------", "All Items", "Tires", "Head Lights", "Wind Shield", "Engines", "Side Mirrors", "Rear Mirror", "Brakes", "Hood", "Front Door", "Back Door", "Fuel Tank", "Transmission" }));
        folderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FolderActionPerformed(evt);
            }
        });

        couponName.setText("Coupon Code:");

        proName.setText("Discount Pct:");

        discountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("--- Warning ---");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("The Discount Settings in this panel is fixed to categories, means you ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("are not possible to set the discount to the specific item you want to.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("We apologize for inconvenience. Hope you enjoy anyway. Thank you!");

        currCouponLabel.setText("Current Coupon Code:");

        currCouponText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currCouponText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currCouponTextActionPerformed(evt);
            }
        });

        currCouponDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("%  Off  Discount");

        CouponDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CouponDiscountActionPerformed(evt);
            }
        });

        jLabel7.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(couponName)
                                                    .addComponent(proName))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(folderCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(couponText)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(currCouponLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(currCouponText)))
                                        .addGap(35, 70, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(currCouponDiscount)
                                            .addComponent(discountText, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                            .addComponent(CouponDiscount))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(proPercent)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(discountSet, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(couponSet, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(proTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(proTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountSet)
                    .addComponent(proPercent)
                    .addComponent(folderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proName)
                    .addComponent(discountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(couponSet)
                    .addComponent(couponText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(couponName)
                    .addComponent(CouponDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currCouponLabel)
                    .addComponent(currCouponText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currCouponDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    public static boolean isNumber(String string) {
    if (string == null || string.isEmpty()) {
        return false;
    }
    int i = 0;
    if (string.charAt(0) == '-') {
        if (string.length() > 1) {
            i++;
        } else {
            return false;
        }
    }
    for (; i < string.length(); i++) {
        if (!Character.isDigit(string.charAt(i))) {
            return false;
        }
    }
    return true;
    }
    
    
    
    private void discountSetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discountSetMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_discountSetMouseClicked

    private void discountSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountSetActionPerformed
        String folderCat = (String)folderCombo.getSelectedItem();
                
        if(isNumber(discountText.getText()) == false){
            JOptionPane.showMessageDialog(framePro, 
                        "You Must Enter a Number.");
        }
        else if(discountText.getText().length()>2){
            JOptionPane.showMessageDialog(framePro, 
                        "Discount Rate must be lower than 100%.");
        }
        else if(discountText.getText().equals("")){
            JOptionPane.showMessageDialog(framePro, 
                        "You Must Enter the Discount Rate.");
        }
        else if(folderCat.equals("------")){
            JOptionPane.showMessageDialog(framePro, 
                        "You Must Select a Category.");
        }
        else{
            if(folderCat.equals("All Items")){
            MainFunc.DiscountApply("Tires", discountText.getText());
            MainFunc.DiscountApply("Head Lights", discountText.getText());
            MainFunc.DiscountApply("Wind Shield", discountText.getText());
            MainFunc.DiscountApply("Engines", discountText.getText());
            MainFunc.DiscountApply("Side Mirrors", discountText.getText());
            MainFunc.DiscountApply("Rear Mirror", discountText.getText());
            MainFunc.DiscountApply("Brakes", discountText.getText());
            MainFunc.DiscountApply("Hood", discountText.getText());
            MainFunc.DiscountApply("Front Door", discountText.getText());
            MainFunc.DiscountApply("Back Door", discountText.getText());
            MainFunc.DiscountApply("Fuel Tank", discountText.getText());
            MainFunc.DiscountApply("Transmission", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<All Items> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Tires")){
            MainFunc.DiscountApply("Tires", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Tires> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Head Lights")){
            MainFunc.DiscountApply("Head Lights", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Head Lights> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Wind Shield")){
            MainFunc.DiscountApply("Wind Shield", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Wind Shield> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Engines")){
            MainFunc.DiscountApply("Engines", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Engines> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Side Mirrors")){
            MainFunc.DiscountApply("Side Mirrors", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Side Mirrors> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Rear Mirror")){
            MainFunc.DiscountApply("Rear Mirror", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Rear Mirror> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Brakes")){
            MainFunc.DiscountApply("Brakes", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Brakes> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Hood")){
            MainFunc.DiscountApply("Hood", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Hood> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Front Door")){
            MainFunc.DiscountApply("Front Door", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Front Door> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Fuel Tank")){
            MainFunc.DiscountApply("Fuel Tank", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Fuel Tank> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Transmission")){
            MainFunc.DiscountApply("Transmission", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Transmission> now have a "+discountText.getText()+"% off.");
            }
            else if(folderCat.equals("Hood")){
            MainFunc.DiscountApply("Hood", discountText.getText());
            JOptionPane.showMessageDialog(framePro, 
                        "<Hood> now have a "+discountText.getText()+"% off.");
            }
        }
        discountText.setText("");
        folderCombo.setSelectedItem("------");
        
    }//GEN-LAST:event_discountSetActionPerformed

    private void couponSetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_couponSetMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_couponSetMouseClicked

    private void couponButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couponButtonActionPerformed
        if(couponText.getText().equals("")||CouponDiscount.getText().equals("")){
            
            JOptionPane.showMessageDialog(framePro, 
                    "Please Enter Coupon Code & Discount Percentage!");
            
        }
        else if(isNumber(CouponDiscount.getText()) == false){
            JOptionPane.showMessageDialog(framePro, 
                        "You Must Enter a Number.");
        }
        else if(CouponDiscount.getText().length()>2){
            JOptionPane.showMessageDialog(framePro, 
                        "Discount Rate must be lower than 100%.");
        }
        else{    
        BufferedWriter writer;
            try
    {
    File file = new File("CouponCode.txt");
    file.createNewFile();

    writer = new BufferedWriter(new FileWriter(file));

                writer.write(couponText.getText()+"###"+CouponDiscount.getText());
                writer.newLine();
                //System.out.println(SEAList[i]);
    
    writer.close();

    }
    catch(FileNotFoundException e)
    {
        System.out.println("File Not Found");
        //System.exit( 1 );
    }
    catch(IOException e)
    {
        System.out.println("something messed up");
        //System.exit( 1 );
    }
            JOptionPane.showMessageDialog(framePro, 
                    "Coupon Code Set to <"+couponText.getText()+"> with <"+CouponDiscount.getText()+"%> Off! ");
            couponText.setText("");
            CouponDiscount.setText("");
        }
        
        currCouponText.setEditable(false);
        currCouponDiscount.setEditable(false);
        Cdetail = MainFunc.RTFCoupon(MainFunc.SpeciPathOri("")+"CouponCode.txt");
        currCouponText.setText(Cdetail[0]);
        currCouponDiscount.setText(Cdetail[1]);
    }//GEN-LAST:event_couponButtonActionPerformed

    private void couponCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couponCodeActionPerformed
        
    }//GEN-LAST:event_couponCodeActionPerformed

    private void FolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FolderActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        couponText.setText("");
        discountText.setText("");
        CouponDiscount.setText("");
        folderCombo.setSelectedItem("------");
    }//GEN-LAST:event_formWindowClosed

    private void discountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTextActionPerformed

    private void currCouponTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currCouponTextActionPerformed
        // TODO add your handling code here:
        //currCouponText.setEditable(false);
        
        
    }//GEN-LAST:event_currCouponTextActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        File f = new File("CouponCode.txt");
        if(f.exists() && !f.isDirectory()) { 
            currCouponText.setEditable(false);
            currCouponDiscount.setEditable(false);
            Cdetail = MainFunc.RTFCoupon(MainFunc.SpeciPathOri("")+"CouponCode.txt");
            currCouponText.setText(Cdetail[0]);
            currCouponDiscount.setText(Cdetail[1]);
        }
        else{
                    try
    {
    
    f.createNewFile();

    

    }
    catch(FileNotFoundException e)
    {
        System.out.println("File Not Found");
        //System.exit( 1 );
    }
    catch(IOException e)
    {
        System.out.println("something messed up");
        //System.exit( 1 );
    }
            currCouponText.setEditable(false);
            currCouponDiscount.setEditable(false);
            Cdetail = MainFunc.RTFCoupon(MainFunc.SpeciPathOri("")+"CouponCode.txt");
            currCouponText.setText(Cdetail[0]);
            currCouponDiscount.setText(Cdetail[1]);
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void CouponDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CouponDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CouponDiscountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CouponDiscount;
    private javax.swing.JLabel couponName;
    private javax.swing.JButton couponSet;
    private javax.swing.JTextField couponText;
    private javax.swing.JTextField currCouponDiscount;
    private javax.swing.JLabel currCouponLabel;
    private javax.swing.JTextField currCouponText;
    private javax.swing.JButton discountSet;
    private javax.swing.JTextField discountText;
    private javax.swing.JComboBox folderCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel proName;
    private javax.swing.JLabel proPercent;
    private javax.swing.JLabel proTitle;
    // End of variables declaration//GEN-END:variables
}
